version: '3.7'
services:
  appseed-app:
    container_name: appseed_app
    env_file: .env
    build: .
    ports:
      - "5005:5005"
networks:
  default:
    name: hardware_engine_hw-engine
    external: true
 
